# Generated by Django 3.1.5 on 2021-01-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, verbose_name='KIND')),
                ('title', models.CharField(max_length=100, verbose_name='TITLE')),
                ('author', models.CharField(max_length=50, verbose_name='AUTHOR')),
                ('display', models.CharField(max_length=200, verbose_name='DISPLAY')),
            ],
        ),
    ]
